# Generated by Django 2.0.6 on 2020-03-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20200305_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno', unique=Exception),
        ),
    ]
