# Generated by Django 2.0.6 on 2020-03-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_auto_20200305_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno'),
        ),
    ]
