# Generated by Django 2.0.6 on 2020-03-13 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_auto_20200306_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listado',
            name='ciclo',
        ),
        migrations.AddField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 18, 36, 9, 5218)),
        ),
    ]
