# Generated by Django 2.0.6 on 2020-03-21 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_auto_20200320_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 13, 9, 26, 40303)),
        ),
    ]
