# Generated by Django 2.0.6 on 2020-03-22 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0008_auto_20200321_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 11, 20, 26, 590939)),
        ),
    ]
