# Generated by Django 2.0.6 on 2020-03-23 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0009_auto_20200322_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 17, 0, 41, 998922)),
        ),
    ]
