# Generated by Django 2.0.6 on 2020-03-23 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0012_auto_20200323_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listado',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 20, 51, 41, 733857)),
        ),
    ]
