# Generated by Django 2.0.6 on 2020-03-23 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
        ('lista', '0015_auto_20200323_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='listado',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodo.Periodo'),
        ),
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 23, 30, 54, 545735)),
        ),
    ]
