# Generated by Django 2.0.6 on 2020-03-24 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0016_auto_20200323_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 24, 0, 5, 50, 902258)),
        ),
    ]
