# Generated by Django 2.0.6 on 2020-03-31 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0027_auto_20200331_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 31, 21, 51, 46, 330272, tzinfo=utc)),
        ),
    ]
