# Generated by Django 2.0.6 on 2020-03-31 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0028_auto_20200331_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 3, 31, 22, 4, 53, 106536, tzinfo=utc)),
        ),
    ]
