# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0029_auto_20200331_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listado',
            options={'ordering': ['-periodo'], 'verbose_name': 'listado', 'verbose_name_plural': 'listados'},
        ),
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 19, 50, 36, 334173, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='listado',
            table='listado',
        ),
    ]
