# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0030_auto_20200402_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
