# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0031_auto_20200402_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='listado',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Matriculado'), (1, 'Retirado'), (2, 'Suspendido')], default=0, null=True),
        ),
    ]
