# Generated by Django 2.0.6 on 2020-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1, unique=True)),
            ],
            options={
                'verbose_name': 'aula',
                'db_table': 'aula',
                'verbose_name_plural': 'aulas',
                'ordering': ['-numero'],
            },
        ),
    ]
