# Generated by Django 2.0.6 on 2020-03-05 21:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='docente/%Y/%m/%d')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'docente',
                'db_table': 'docente',
                'verbose_name_plural': 'docentes',
                'ordering': ['-cedula'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
