# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_docente_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Retirado'), (2, 'Suspendido')], default=0, null=True),
        ),
    ]
