# Generated by Django 2.0.6 on 2020-03-31 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar', '0009_asignar_curso'),
        ('horario', '0004_auto_20200306_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='curso',
        ),
        migrations.AddField(
            model_name='horario',
            name='asignar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignar.Asignar'),
        ),
    ]
