# Generated by Django 2.0.6 on 2020-03-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0005_auto_20200331_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='docente',
        ),
    ]
