# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0006_remove_horario_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='ciclo',
        ),
    ]
