# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0031_auto_20200402_1542'),
        ('horario', '0007_remove_horario_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='listado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lista.Listado'),
        ),
    ]
