# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_docente_rol'),
        ('curso', '0003_remove_curso_asignar'),
        ('horario', '0008_horario_listado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='asignar',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='listado',
        ),
        migrations.AddField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.Docente'),
        ),
    ]
