# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar', '0010_auto_20200402_1450'),
        ('horario', '0009_auto_20200402_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='docente',
        ),
        migrations.AddField(
            model_name='horario',
            name='asignar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignar.Asignar'),
        ),
    ]
