# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0010_auto_20200403_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='asist_alum',
            field=models.IntegerField(choices=[(1, 'Falta'), (2, 'Registrado')], default=1),
        ),
    ]
