# Generated by Django 2.0.6 on 2020-03-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('asignar', '0004_auto_20200305_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
