# Generated by Django 2.0.6 on 2020-03-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignar', '0007_auto_20200323_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignar',
            name='curso',
        ),
    ]
