# Generated by Django 2.0.6 on 2020-03-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_curso_asignar'),
        ('asignar', '0008_remove_asignar_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
