# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar', '0010_auto_20200402_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activo'), (1, 'Retirado'), (2, 'Suspendido')], default=0),
        ),
    ]
