# Generated by Django 2.0.6 on 2020-03-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcial',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
