# Generated by Django 2.0.6 on 2020-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (0, 'Femenino')], default=1)),
            ],
            options={
                'verbose_name': 'representante',
                'db_table': 'representante',
                'verbose_name_plural': 'representante',
                'ordering': ['-nombres', '-cedula', '-apellidos'],
            },
        ),
    ]
