# Generated by Django 2.0.6 on 2020-03-05 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asistencia', models.IntegerField(blank=True, choices=[(1, 'Presente'), (0, 'Falta')], default=0, null=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
