# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_auto_20200305_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencias',
            options={'verbose_name': 'asistencia', 'verbose_name_plural': 'asistencias'},
        ),
        migrations.AlterModelTable(
            name='asistencias',
            table='asistencia',
        ),
    ]
