# Generated by Django 2.0.6 on 2020-03-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_asignar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='asignar',
        ),
    ]
