# Generated by Django 2.0.6 on 2020-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1, unique=True)),
            ],
            options={
                'db_table': 'quimestre',
                'verbose_name': 'quimestre',
                'verbose_name_plural': 'quimestres',
            },
        ),
    ]
