# Generated by Django 2.0.6 on 2020-03-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.Horario')),
            ],
            options={
                'verbose_name': 'registro',
                'db_table': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-id'],
            },
        ),
    ]
