# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Retirado'), (2, 'Suspendido')], default=0, null=True),
        ),
    ]
