# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alumno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Retirado'), (2, 'Suspendido'), (3, 'Inactivo')], default=3, null=True),
        ),
    ]
