# Generated by Django 2.0.6 on 2020-03-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quimestre_1', models.FloatField(default=0)),
                ('Parcial_1_q_1', models.FloatField(default=0)),
                ('Parcial_2_q_1', models.FloatField(default=0)),
                ('Parcial_3_q_1', models.FloatField(default=0)),
                ('Quimestre_2', models.FloatField(default=0)),
                ('Parcial_1_q_2', models.FloatField(default=0)),
                ('Parcial_2_q_2', models.FloatField(default=0)),
                ('Parcial_3_q_2', models.FloatField(default=0)),
                ('Asistencias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencias.Asistencias')),
            ],
        ),
    ]
