# Generated by Django 2.0.6 on 2020-03-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='Nota_final',
            field=models.FloatField(default=0),
        ),
    ]
