# Generated by Django 2.0.6 on 2020-03-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_auto_20200320_1232'),
        ('asignar', '0004_auto_20200305_2124'),
        ('notas', '0002_notas_nota_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Asistencias',
        ),
        migrations.AddField(
            model_name='notas',
            name='Asignar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignar.Asignar'),
        ),
        migrations.AddField(
            model_name='notas',
            name='Listado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lista.Listado'),
        ),
    ]
