# Generated by Django 2.0.6 on 2020-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20200320_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Nota_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Quimestre_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Quimestre_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
