# Generated by Django 2.0.6 on 2020-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_auto_20200321_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_1',
            field=models.FloatField(default=0),
        ),
    ]
