# Generated by Django 2.0.6 on 2020-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_auto_20200321_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Nota_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Quimestre_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Quimestre_2',
            field=models.IntegerField(default=0),
        ),
    ]
