# Generated by Django 2.0.6 on 2020-03-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcial', '0002_auto_20200325_1837'),
        ('notas', '0006_auto_20200322_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Parcial_1_q_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Parcial_1_q_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Parcial_2_q_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Parcial_2_q_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Parcial_3_q_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Parcial_3_q_2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Quimestre_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Quimestre_2',
        ),
        migrations.AddField(
            model_name='notas',
            name='Nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcial.Parcial'),
        ),
    ]
