# Generated by Django 2.0.6 on 2020-03-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_auto_20200325_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Nota',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Nota_final',
        ),
        migrations.AddField(
            model_name='notas',
            name='Parcial_1_q_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Parcial_1_q_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Parcial_2_q_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Parcial_2_q_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Parcial_3_q_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Parcial_3_q_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Quimestre_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notas',
            name='Quimestre_2',
            field=models.IntegerField(default=1),
        ),
    ]
