# Generated by Django 2.0.6 on 2020-03-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_auto_20200325_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='Quimestre_1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='Quimestre_2',
        ),
    ]
