# Generated by Django 2.0.6 on 2020-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_auto_20200325_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_2',
            field=models.IntegerField(default=0),
        ),
    ]
