# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-18 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0011_auto_20200402_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='examen_final',
            field=models.IntegerField(default=0),
        ),
    ]
