# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0012_notas_examen_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_1',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_1_q_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_2_q_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='Parcial_3_q_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='examen_final',
            field=models.FloatField(default=0),
        ),
    ]
