# Generated by Django 2.0.6 on 2020-03-05 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(default=datetime.datetime.now)),
                ('periodo_fin', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
