# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-periodo_inicio'], 'verbose_name': 'periodo', 'verbose_name_plural': 'periodos'},
        ),
        migrations.AlterModelTable(
            name='periodo',
            table='periodo',
        ),
    ]
